name: Build and Deploy Python app to Azure Web App - alphavue-app-live

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Set default permissions for all jobs in this workflow
permissions:
  contents: read # Default read permission for all jobs
  id-token: write # Required for OIDC authentication with Azure

jobs:
  build:
    runs-on: ubuntu-latest
    # Explicitly grant write permission for contents for this job to upload artifacts
    permissions:
      contents: write # Override default to allow writing (uploading artifacts)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Upload artifact for deployment jobs
        # Using v3 of upload-artifact for broader compatibility
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            .
            !venv/
            !.git/
            !.github/
            # Ensure your data files are included if they are not directly in the root but needed for deployment
            # Example if you have a 'data' folder in the root:
            # data/

  deploy:
    runs-on: ubuntu-latest
    needs: build # This job depends on the 'build' job completing successfully
    permissions:
      id-token: write # Required for OIDC authentication with Azure
      contents: read # Required for downloading artifact

    steps:
      - name: Download artifact from build job
        # Using v3 of download-artifact for consistency
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3 # Using v3 for consistency if needed, but v3/v4/v5 are often compatible
        id: deploy-to-webapp
        with:
          app-name: 'alphavue-app-live'
          slot-name: 'Production'
          startup-command: 'streamlit run portfolio_app.py --server.port 8000 --server.enableCORS false --server.enableXsrfProtection false'
