# .streamlit/secrets.toml

[connections.mysql]
host = "alphavuedb.cjg4kc862qqu.ap-south-1.rds.amazonaws.com" 
user = "admin"  
password = "AlphaDB!2025" 
database = "alphavue"

[app_secrets]
admin_code = "Alphavueadmin2025"